import type { Generator } from "../generator.js";
import type { GeneratedFile, CompilationContext, ResolvedProfile } from "../types.js";

export class HooksGenerator implements Generator {
  name = "hooks";

  generate(ctx: CompilationContext): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Collect all profiles that have onReview rules
    const reviewProfiles = ctx.profiles.filter(p => p.onReview.length > 0);
    if (reviewProfiles.length === 0) return files;

    // Generate hook scripts
    for (const profile of reviewProfiles) {
      const name = profile.name.toLowerCase();
      const path = `.claude/hooks/review-${name}.sh`;
      const content = generateHookScript(profile);
      files.push({ path, content });
    }

    // Generate settings.json
    const settingsContent = generateSettings(reviewProfiles, ctx);
    files.push({ path: ".claude/settings.json", content: settingsContent });

    return files;
  }
}

function generateHookScript(profile: ResolvedProfile): string {
  const name = profile.name;
  const lines: string[] = [];

  lines.push("#!/bin/bash");
  lines.push(`# Auto-generated by LangC transpiler — ${name} profile ON_REVIEW`);
  lines.push('INPUT=$(cat)');
  lines.push('FILE=$(echo "$INPUT" | jq -r \'.tool_input.file_path // empty\')');
  lines.push("");
  lines.push('if [ -z "$FILE" ]; then');
  lines.push("  exit 0");
  lines.push("fi");
  lines.push("");

  // Generate grep checks based on review rules
  for (const rule of profile.onReview) {
    lines.push(`# ${rule}`);
  }
  lines.push("");
  lines.push("exit 0");
  lines.push("");

  return lines.join("\n");
}

function generateSettings(
  reviewProfiles: ResolvedProfile[],
  ctx: CompilationContext,
): string {
  const hookCommands = reviewProfiles.map(p => ({
    type: "command",
    command: `bash .claude/hooks/review-${p.name.toLowerCase()}.sh`,
  }));

  // Build the Stop hook prompt from all review rules
  const allReviewItems = reviewProfiles.flatMap(p =>
    p.onReview.map(r => `(${p.name}) ${r}`),
  );

  const stopPrompt = [
    "Review all files created/modified in this session. Check:",
    ...allReviewItems.map((item, i) => `(${i + 1}) ${item}`),
    "Report violations as ✗, warnings as ⚠, passes as ✓.",
  ].join(" ");

  const settings: Record<string, unknown> = {
    hooks: {
      PostToolUse: [
        {
          matcher: "Write|Edit",
          hooks: hookCommands,
        },
      ],
      Stop: [
        {
          hooks: [
            {
              type: "agent",
              prompt: stopPrompt,
              timeout: 120,
            },
          ],
        },
      ],
    },
  };

  return JSON.stringify(settings, null, 2) + "\n";
}
