import type { Generator } from "../generator.js";
import type { GeneratedFile, CompilationContext, ResolvedProfile } from "../types.js";

/** Maps common ON_REVIEW rule keywords to grep patterns. */
const rulePatterns: { keyword: string; pattern: string; message: string }[] = [
  {
    keyword: "raw sql",
    pattern: '(f".*SELECT|f".*INSERT|f".*UPDATE|f".*DELETE|\\+.*SELECT|\\+.*INSERT)',
    message: "Possible raw SQL string construction detected",
  },
  {
    keyword: "sql string",
    pattern: '(f".*SELECT|f".*INSERT|f".*UPDATE|f".*DELETE|\\+.*SELECT|\\+.*INSERT)',
    message: "Possible SQL string concatenation detected",
  },
  {
    keyword: "stack trace",
    pattern: "(traceback\\.print|print_exc|e\\.stackTrace|console\\.error\\(err)",
    message: "Possible stack trace exposure detected",
  },
  {
    keyword: "hardcoded",
    pattern: '(password\\s*=\\s*"|api_key\\s*=\\s*"|secret\\s*=\\s*")',
    message: "Possible hardcoded credential detected",
  },
  {
    keyword: "credential",
    pattern: '(password\\s*=\\s*"|api_key\\s*=\\s*"|secret\\s*=\\s*")',
    message: "Possible hardcoded credential detected",
  },
  {
    keyword: "port",
    pattern: '(:[0-9]{4,5}[^0-9]|localhost:[0-9])',
    message: "Possible hardcoded port or URL detected",
  },
  {
    keyword: "exceeds 300 lines",
    pattern: "",  // special case: line count check
    message: "File exceeds 300 lines",
  },
];

export class HooksGenerator implements Generator {
  name = "hooks";

  generate(ctx: CompilationContext): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    // Collect all profiles that have onReview rules
    const reviewProfiles = ctx.profiles.filter(p => p.onReview.length > 0);
    if (reviewProfiles.length === 0) return files;

    // Generate hook scripts
    for (const profile of reviewProfiles) {
      const name = profile.name.toLowerCase();
      const path = `.claude/hooks/review-${name}.sh`;
      const content = generateHookScript(profile);
      files.push({ path, content });
    }

    // Generate settings.json
    const settingsContent = generateSettings(reviewProfiles, ctx);
    files.push({ path: ".claude/settings.json", content: settingsContent });

    return files;
  }
}

function generateHookScript(profile: ResolvedProfile): string {
  const name = profile.name;
  const lines: string[] = [];

  lines.push("#!/bin/bash");
  lines.push(`# Auto-generated by LangC transpiler — ${name} profile ON_REVIEW`);
  lines.push('INPUT=$(cat)');
  lines.push('FILE=$(echo "$INPUT" | jq -r \'.tool_input.file_path // empty\')');
  lines.push("");
  lines.push('if [ -z "$FILE" ]; then');
  lines.push("  exit 0");
  lines.push("fi");
  lines.push("");

  for (const rule of profile.onReview) {
    lines.push(`# ${rule}`);

    // Try to match a grep pattern for this rule
    const ruleLower = rule.toLowerCase();
    let matched = false;

    // Special case: line count check
    if (ruleLower.includes("exceeds") && ruleLower.includes("lines")) {
      const limitMatch = ruleLower.match(/(\d+)\s*lines/);
      const limit = limitMatch ? limitMatch[1] : "300";
      lines.push(`LINE_COUNT=$(wc -l < "$FILE" 2>/dev/null || echo 0)`);
      lines.push(`if [ "$LINE_COUNT" -gt ${limit} ]; then`);
      lines.push(`  echo "⚠ ${name}: File $FILE has $LINE_COUNT lines (limit: ${limit})" >&2`);
      lines.push("fi");
      lines.push("");
      matched = true;
    }

    if (!matched) {
      for (const rp of rulePatterns) {
        if (rp.pattern && ruleLower.includes(rp.keyword)) {
          lines.push(`if grep -qE "${rp.pattern}" "$FILE" 2>/dev/null; then`);
          lines.push(`  echo "⚠ ${name}: ${rp.message} in $FILE" >&2`);
          lines.push(`  echo "  ${rule}" >&2`);
          lines.push("fi");
          lines.push("");
          matched = true;
          break;
        }
      }
    }

    if (!matched) {
      // No pattern match — leave as comment-only
      lines.push("");
    }
  }

  lines.push("exit 0");
  lines.push("");

  return lines.join("\n");
}

function generatePermissions(ctx: CompilationContext): { allow: string[]; deny: string[] } {
  const allow: string[] = [];
  const deny: string[] = [];
  const projectDir = `./${ctx.projectName}`;

  // Allow reading everything
  allow.push("Read(./**)");

  // Allow writing/editing within the project directory
  allow.push(`Write(${projectDir}/**)`);
  allow.push(`Edit(${projectDir}/**)`);

  // Allow common build/test commands based on LNG
  const lngs = new Set<string>();
  for (const block of ctx.createBlocks) {
    for (const prop of block.properties) {
      if (prop.kind === "LngProperty") lngs.add(prop.value.toLowerCase());
    }
  }

  if (lngs.has("python")) {
    allow.push("Bash(pytest *)");
    allow.push("Bash(ruff check *)");
    allow.push("Bash(pip install *)");
  }
  if (lngs.has("react") || lngs.has("typescript") || lngs.has("javascript")) {
    allow.push("Bash(npm test *)");
    allow.push("Bash(npm run *)");
    allow.push("Bash(npx *)");
  }
  if (lngs.has("go")) {
    allow.push("Bash(go test *)");
    allow.push("Bash(go build *)");
  }
  if (lngs.has("rust")) {
    allow.push("Bash(cargo test *)");
    allow.push("Bash(cargo build *)");
  }

  // Deny dangerous operations
  deny.push("Bash(rm -rf *)");
  deny.push("Write(./.env*)");
  deny.push("Edit(./.env*)");
  deny.push("Write(./**/credentials*)");
  deny.push("Write(./**/*.pem)");

  return { allow, deny };
}

function generateSettings(
  reviewProfiles: ResolvedProfile[],
  ctx: CompilationContext,
): string {
  const hookCommands = reviewProfiles.map(p => ({
    type: "command",
    command: `bash .claude/hooks/review-${p.name.toLowerCase()}.sh`,
  }));

  // Build the Stop hook prompt from all review rules
  const allReviewItems = reviewProfiles.flatMap(p =>
    p.onReview.map(r => `(${p.name}) ${r}`),
  );

  const stopPrompt = [
    "Review all files created/modified in this session. Check:",
    ...allReviewItems.map((item, i) => `(${i + 1}) ${item}`),
    "Report violations as ✗, warnings as ⚠, passes as ✓.",
  ].join(" ");

  const permissions = generatePermissions(ctx);

  const settings: Record<string, unknown> = {
    permissions,
    hooks: {
      PostToolUse: [
        {
          matcher: "Write|Edit",
          hooks: hookCommands,
        },
      ],
      Stop: [
        {
          hooks: [
            {
              type: "agent",
              prompt: stopPrompt,
              timeout: 120,
            },
          ],
        },
      ],
    },
  };

  return JSON.stringify(settings, null, 2) + "\n";
}
