import { TokenType } from "./tokens.js";

export const keywords: Record<string, TokenType> = {
  IMPORT: TokenType.IMPORT,
  FROM: TokenType.FROM,
  PROJECT: TokenType.PROJECT,
  PROFILE: TokenType.PROFILE,
  CREATE: TokenType.CREATE,
  UPDATE: TokenType.UPDATE,
  ADD: TokenType.ADD,
  REMOVE: TokenType.REMOVE,
  METHOD: TokenType.METHOD,
  DISPLAY: TokenType.DISPLAY,
  TABLE: TokenType.TABLE,
  DB: TokenType.DB,
  API: TokenType.API,
  WEBUI: TokenType.WEBUI,
  FNC: TokenType.FNC,
  LNG: TokenType.LNG,
  FRAMEWORK: TokenType.FRAMEWORK,
  SCOPE: TokenType.SCOPE,
  REFERENCE: TokenType.REFERENCE,
  DEPENDS: TokenType.DEPENDS,
  PROFILES: TokenType.PROFILES,
  ROLE: TokenType.ROLE,
  RULES: TokenType.RULES,
  PATTERNS: TokenType.PATTERNS,
  ON_REVIEW: TokenType.ON_REVIEW,
  EXTENDS: TokenType.EXTENDS,
  EXCEPT: TokenType.EXCEPT,
  GATE: TokenType.GATE,
  PUBLIC: TokenType.PUBLIC,
  GET: TokenType.GET,
  POST: TokenType.POST,
  PUT: TokenType.PUT,
  DELETE: TokenType.DELETE,
  PATCH: TokenType.PATCH,
  none: TokenType.None,
  full: TokenType.Full,
  skeleton: TokenType.Skeleton,
  prototype: TokenType.Prototype,
  auto: TokenType.Auto,
  update: TokenType.Update,
};
